services:
  yarp-gateway:
    image: app.demo/yarp-gateway:latest
    build:
      context: ./YarpGateway/
      dockerfile: Dockerfile
    ports:
      - "8080:5325"
    depends_on:
      - product-service
      - review-service
    networks:
      - app_network

  product-service:
    image: app.demo/product-service:latest
    build:
      context: ./ProductService/
      dockerfile: Dockerfile
    networks:
      - app_network

  review-service:
    image: app.demo/review-service:latest
    build:
      context: ./ReviewService/
      dockerfile: Dockerfile
    networks:
      - app_network


networks:
  app_network:
    driver: bridge